tokens:
  - chainName: kasplex
    standard: EvmHypSynthetic
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: "0x64592C9a33453b4E91657C2c8b253B86CD26EC90"
    connections:
      - token: ethereum|base|0x001cfbd182c74107B70bfcbbCD709E1d73cde0f2
  - chainName: base
    standard: EvmHypCollateral
    decimals: 6
    symbol: USDC
    name: USD Coin
    addressOrDenom: "0x001cfbd182c74107B70bfcbbCD709E1d73cde0f2"
    collateralAddressOrDenom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    connections:
      - token: ethereum|kasplex|0x64592C9a33453b4E91657C2c8b253B86CD26EC90
