tokens:
  - chainName: kasplextestnet
    standard: EvmHypCollateral
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0x35985666e8784b49d1377F0e5a925A5cA18F56AC"
    collateralAddressOrDenom: "0x58Dc3C68b533c800cB0667Eef052f4E67a0E5cBe"
    connections:
      - token: ethereum|basesepolia|0x8C3109Fc7D247Df0AEc2e3620b38B0EB1Ce99AbD
    logoURI: /deployments/warp_routes/USDT/logo.svg
  - chainName: basesepolia
    standard: EvmHypSynthetic
    decimals: 18
    symbol: USDT
    name: USDT
    addressOrDenom: "0x8C3109Fc7D247Df0AEc2e3620b38B0EB1Ce99AbD"
    connections:
      - token: ethereum|kasplextestnet|0x35985666e8784b49d1377F0e5a925A5cA18F56AC
    logoURI: /deployments/warp_routes/USDT/logo.svg
