defaultHook:
  type: merkleTreeHook
defaultIsm:
  relayer: "0xeDBdD8d6612d55cFCF746188744bfB3356567f4f"
  type: trustedRelayerIsm
owner: "0xeDBdD8d6612d55cFCF746188744bfB3356567f4f"
proxyAdmin:
  owner: "0xeDBdD8d6612d55cFCF746188744bfB3356567f4f"
requiredHook:
  hooks:
    - beneficiary: "0xeDBdD8d6612d55cFCF746188744bfB3356567f4f"
      maxProtocolFee: "2000000000000000000"
      owner: "0xeDBdD8d6612d55cFCF746188744bfB3356567f4f"
      protocolFee: "0"
      type: protocolFee
    - beneficiary: "0xeDBdD8d6612d55cFCF746188744bfB3356567f4f"
      oracleConfig:
        base:
          gasPrice: "3592183"
          tokenDecimals: 18
          tokenExchangeRate: "11000000000"
        bsc:
          gasPrice: "100000000"
          tokenDecimals: 18
          tokenExchangeRate: "3120157781"
        kasplex:
          gasPrice: "2001000000000"
          tokenDecimals: 18
          tokenExchangeRate: "151409"
      oracleKey: "0xeDBdD8d6612d55cFCF746188744bfB3356567f4f"
      overhead:
        base: 75000
        bsc: 75000
        kasplex: 75000
      owner: "0xeDBdD8d6612d55cFCF746188744bfB3356567f4f"
      type: interchainGasPaymaster
  type: aggregationHook

