owner: "0xae44946077d5c32ffbdccf97dddda689904caaaa"
defaultIsm:
  type: trustedRelayerIsm
  relayer: "0xae44946077d5c32ffbdccf97dddda689904caaaa"
defaultHook:
  type: merkleTreeHook
requiredHook:
  type: aggregationHook
  hooks:
    - owner: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      type: protocolFee
      beneficiary: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      maxProtocolFee: "100000000000000000000000000000000000000"
      protocolFee: "100000000000000000000000000000000000"
    - owner: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      type: interchainGasPaymaster
      beneficiary: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      oracleKey: "0xaE44946077D5C32FFBDcCF97ddDdA689904caAAa"
      overhead:
        kasplex: 75000
      oracleConfig:
        kasplex:
          gasPrice: "2001000000000"
          tokenExchangeRate: "7550901687027342"
          tokenDecimals: 8
proxyAdmin:
  owner: "0xae44946077d5c32ffbdccf97dddda689904caaaa"
